#!/bin/sh -e

# Author: Andreas Baumann <abaumann@yahoo.com>

case "$2" in
	DEINSTALL)
		# forced stop, ignore errors
		pkill wolframed || true
		;;
	
	POST-DEINSTALL)
		# don't ignore errors here
		set -e

		# remove log directory and it's contents
		if test -d /var/log/wolframe; then
			rm -rf /var/log/wolframe
		fi
		
		# dito lock directory
		if test -d /var/run/wolframe; then
			rm -rf /var/run/wolframe
		fi

		# remove wolframe user (and primary group implicitly)
		getent group wolframe >/dev/null && /usr/sbin/pw userdel wolframe
		
		echo "Remove 'wolframed_enable' from '/etc/rc.conf' manually!"
		echo
		;;

	*)
		echo "dscript called with unknown argument $2" >&2
		exit 1
		;;
esac

exit 0
