#!/bin/sh

# either --cflags, --ldflags or --libs 
FLAG=$1

# the location of python3-config
PYTHON3_CONFIG=$2

# bail out fast if we already have a cache file, otherwise building is far too slow!
MAKEFILE_DIR="$3/$4"
if test -f "${MAKEFILE_DIR}/makefiles/gmake/python.vars" &&
   test -f "${MAKEFILE_DIR}/makefiles/gmake/python.mk.vars"; then
	. "${MAKEFILE_DIR}/makefiles/gmake/python.vars"
else

	if test ! -x "$PYTHON3_CONFIG"; then
		echo "ERROR: no '$PYTHON3_CONFIG' executable found!" >&2
		exit 1
	fi
		

	PYTHON_CFLAGS=`$PYTHON3_CONFIG --cflags`
	PYTHON_LDFLAGS=`$PYTHON3_CONFIG --ldflags`
	PYTHON_LIBS=`$PYTHON3_CONFIG --libs`

	# Do some plaform specific fixes, python3-config is most of the times wrong!
	UNAME_SYSTEM=`(uname -s) 2>/dev/null`
	UNAME_RELEASE=`(uname -r) 2>/dev/null`
	case "$UNAME_SYSTEM.$UNAME_RELEASE" in
		Linux*)
			# Wstrict\-prototypes is not valid for C++ code
			PYTHON_CFLAGS=`echo $PYTHON_CFLAGS | sed 's|\-Wstrict\-prototypes||'`
			;;
		
		SunOS*)
			# Wstrict\-prototypes is not valid for C++ code
			PYTHON_CFLAGS=`echo $PYTHON_CFLAGS | sed 's|\-Wstrict\-prototypes||'`
			# Solaris misses a library path?!
			PYTHON_LDFLAGS="$PYTHON_LDFLAGS -L/opt/csw/python-3.3.2/lib"
			;;

		FreeBSD*8*|FreeBSD*9*)
			# Wrong order of link pathes or missing shared library, creates
			# a mislink with libpython.a and a warning about -fPIC
			PYTHON_LDFLAGS=`echo $PYTHON_LDFLAGS | sed 's|-L/usr/local/lib/python3.3/config-3.3m||'`
			;;
	esac

	# generate the makefile snippet with conditional variables
	# (conditional, so that users can overwrite them
	cat >"${MAKEFILE_DIR}/makefiles/gmake/python.mk.vars" <<EOF
PYTHON_CFLAGS?=$PYTHON_CFLAGS
PYTHON_LDFLAGS?=$PYTHON_LDFLAGS
PYTHON_LIBS?=$PYTHON_LIBS
EOF

	# write the cache file (to protect against constant recomputations!)
	cat >"${MAKEFILE_DIR}/makefiles/gmake/python.vars" <<EOF
PYTHON_CFLAGS="$PYTHON_CFLAGS"
PYTHON_LDFLAGS="$PYTHON_LDFLAGS"
PYTHON_LIBS="$PYTHON_LIBS"
EOF

fi

case "$FLAG" in
	--cflags)		echo $PYTHON_CFLAGS
				;;

	--ldflags)		echo $PYTHON_LDFLAGS
				;;

	--libs)			echo $PYTHON_LIBS
				;;

	*)			echo "unkown flag '$FLAG' requested!"
				exit 1
esac
