TOPDIR = ..\..

SUBDIRS = tests

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\src \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\3rdParty\gtest\include

# Note: libraries are picked automatically on Windows!
INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	Advapi32.lib Ws2_32.lib \
	$(TOPDIR)\src\loadModules.obj \
	$(TOPDIR)\3rdParty\gtest\gtest-all.obj \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwfshared\wfshared.lib

TEST_CPP_BINS = \
	moduleTest.exe

OBJS =

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

moduleTest.exe: moduleTest.obj $(TOPDIR)\src\wolframe.lib

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

# cd tests...: Temporary hotfix to avoid running the module test before having built the modules
local_test:
	@cd tests & $(MAKE) /nologo /f Makefile.w32 test & cd ..
	@-echo @echo off > test.bat
	@-echo PATH=%PATH%;$(BOOST_DIR)\Lib;$(TOPDIR)\src\libwfshared >> test.bat
	@-echo set PATHEXT=%PATHEXT%;.DLL >> test.bat
	@-echo moduleTest >> test.bat
	@-echo echo off >> test.bat
	@-test.bat
