TOPDIR = ../../..

SUBDIRS = number base64 string

-include $(TOPDIR)/makefiles/gmake/platform.mk

ifeq ($(WITH_ICU),1)
SUBDIRS += locale
endif

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

