TOPDIR = ..\..\..

SUBDIRS = number base64

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

# textwolf
!IFDEF WITH_TEXTWOLF
SUBDIRS = \
	$(SUBDIRS) string
!ENDIF

!IFDEF WITH_ICU
SUBDIRS = \
	$(SUBDIRS) locale
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
