TOPDIR = ..\..\..

SUBDIRS = number

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

!IFDEF WITH_ICU
SUBDIRS = \
	$(SUBDIRS) locale
!ENDIF


!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
