#!/usr/bin/expect
#
# Checks an authentication method
#

package require Expect

set timeout 5
log_user 0

puts -nonewline "Authentication TEXTFILE successfull - "

spawn ./authTest TEXTFILE

expect "login: "
send "test\r"
expect "Enter your password:"
send "xx\r"
expect {
	"Authentication succeeded!"	{ puts "OK" }
	"Authentication failed!"	{ puts "ERROR" }
	timeout 			{ puts "Timeout" }
}
