@echo off

nmake /nologo /f Makefile.W32 WITH_SSL=1 WITH_EXPECT=1 WITH_LUA=1 ^
	WITH_SQLITE3=1 WITH_PGSQL=1 WITH_LIBXML2=1 WITH_LIBXSLT=1 ^
	WITH_LIBHPDF=1 WITH_EXAMPLES=1 WITH_ICU=1 WITH_FREEIMAGE=1 ^
	WITH_PYTHON=1 WITH_CJSON=1 WITH_TEXTWOLF=1 DEBUG=1 %*
	
