TOPDIR = .

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

SUBDIRS = src gtest tests clients

!IFDEF WITH_LIBHARU
SUBDIRS = libharu $(SUBDIRS)
!ENDIF

!IFDEF WITH_LUA
SUBDIRS = lua $(SUBDIRS)
!ENDIF

!IFDEF WITH_EXAMPLES
SUBDIRS = $(SUBDIRS) examples
!ENDIF

PACKAGE_NAME = wolframe
PACKAGE_VERSION = 0.0.1

!INCLUDE $(TOPDIR)\makefiles\nmake\top.mk
