TOPDIR = .

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

SUBDIRS = 3rdParty src wtest tests clients

!IFDEF WITH_EXAMPLES
SUBDIRS = $(SUBDIRS) examples
!ENDIF

PACKAGE_NAME = wolframe
PACKAGE_VERSION = 0.0.1

!INCLUDE $(TOPDIR)\makefiles\nmake\top.mk
