TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CFLAGS = \
	/D_WIN32_WINNT=0x504 \
	/wd4146

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504 \
	/wd4146

INCLUDE_DIRS = \
	/I. /I$(TOPDIR)\libgmp \
	/I$(TOPDIR)\mpfr\src

INCLUDE_LDFLAGS =

INCLUDE_LIBS = \
	$(TOPDIR)\mpfr\src\mpfr.lib \
	$(TOPDIR)\libgmp\mpn\mpn.lib \
	$(TOPDIR)\libgmp\gmpcommon.lib

TEST_CPP_BINS = \
	testmpfr_c.exe

all: $(TEST_CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testmpfr_c.exe: testmpfr_c.obj

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo testmpfr_c 12.12312312312312 34.334556443334533 >> test.bat
	@-test.bat
