TOPDIR = ../../../..

SUBDIRS =

-include $(TOPDIR)/makefiles/gmake/platform.mk

INCLUDE_DIRS =

INCLUDE_CXXFLAGS =

INCLUDE_LDFLAGS = \
	-L..

INCLUDE_LIBS =

DYNAMIC_MODULE = \
	missing_symbol.so

CPP_OBJS = \
	missing_symbol.o

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_install:

local_uninstall:

local_test:

