TOPDIR = ../..

SUBDIRS = database audit authentication processor

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_uninstall:
	@-rmdir $(DESTDIR)$(libdir)/wolframe
