TOPDIR = ..\..

SUBDIRS =

# PostgreSQL
!IFDEF WITH_PGSQL
SUBDIRS = \
	$(SUBDIRS) PostgreSQL
!ENDIF

# sqlite3
!IFDEF WITH_SQLITE3
SUBDIRS = \
	$(SUBDIRS) SQLite
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
