TOPDIR = ..\..

SUBDIRS = database audit authentication authorization filter ddlcompiler prnt transaction cmdbind
# Aba: echoProcessor, temporarily disabled, doesn't build on windows
!IFDEF WITH_LUA
SUBDIRS = $(SUBDIRS) lua
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
