TOPDIR = ..\..

SUBDIRS = database audit authentication authorization filter ddlcompiler \
	normalize prnt cmdbind functions timer jobScheduler

!IFDEF WITH_LUA
SUBDIRS = $(SUBDIRS) lua
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
