TOPDIR = ..\..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)"

INCLUDE_LDFLAGS = \
	/LIBPATH:$(TOPDIR)\src\libwfsingleton \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	kernel32.lib advapi32.lib Ws2_32.lib \
	wfsingleton.lib

DYNAMIC_MODULE = \
	mod_test.dll

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(CPP_OBJS) mod_test.obj
	$(LINK) /dll /def:mod_test.def /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:

local_distclean:

local_test: $(DYNAMIC_MODULE)
