TOPDIR = ..

SUBDIRS =

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:
	$(MAKE) -f Makefile.orig PLAT=$(LUA_PLATFORM)

local_clean:
	$(MAKE) -f Makefile.orig PLAT=$(LUA_PLATFORM) clean

local_distclean:

local_install:

local_test:
