TOPDIR = ../../..

SUBDIRS = employee_assignment_convert echo_cmdhandler

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
