TOPDIR = ..

SUBDIRS = AAAA

# all broken on windows due to working telnet
#!IFDEF WITH_EXPECT
#SUBDIRS = \
#	$(SUBDIRS) expect
#!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CPPFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I$(TOPDIR)\include /I. \
	/I$(TOPDIR)\src \
	/I$(TOPDIR)\examples\pecho \
	/I$(TOPDIR)\examples\mtproc \
	/I$(TOPDIR)\examples\iproc \
	/I"$(BOOST_DIR)" \
	/I"$(PLATFORM_SDK_DIR)\Include" \
	/I$(TOPDIR)\gtest\include

# Note: libraries are picked automatically on Windows!
SDK_LDFLAGS = /LIBPATH:"$(PLATFORM_SDK_DIR)\lib"
INCLUDE_LDFLAGS = \
	$(SDK_LDFLAGS) $(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	Advapi32.lib Ws2_32.lib \
	$(TOPDIR)\gtest\gtest-all.obj

TEST_CPP_BINS = \
	threadLeakTest.exe \
	testNamedRetVal.exe \
	versionTest.exe \
	counterTest.exe \
	resolvePathTest.exe \
	singletonTest.exe \
	poolTest.exe \
	logTest.exe \
	protocolArgumentParsing.exe \
	configValueParser.exe
# broken on windows
#	pechoHandler.exe
#	mtprocHandler.exe


OBJS = \

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

threadLeakTest.exe: threadLeakTest.obj $(TOPDIR)\src\wolframe.lib

testNamedRetVal.exe: testNamedRetVal.obj
versionTest.exe: versionTest.obj $(TOPDIR)\src\wolframe.lib
counterTest.exe: counterTest.obj $(TOPDIR)\src\wolframe.lib
resolvePathTest.exe: resolvePathTest.obj $(TOPDIR)\src\wolframe.lib
singletonTest.exe: singletonTest.obj $(TOPDIR)\src\wolframe.lib
poolTest.exe: poolTest.obj $(TOPDIR)\src\wolframe.lib
logTest.exe: logTest.obj $(TOPDIR)\src\wolframe.lib
protocolArgumentParsing.exe: protocolArgumentParsing.obj $(TOPDIR)\src\wolframe.lib
configValueParser.exe: configValueParser.obj $(TOPDIR)\src\wolframe.lib
# broken on windows
#pechoHandler.exe: pechoHandler.obj

# broken on windows
#MTPROC_GTEST_OBJS=$(TOPDIR)\examples\mtproc\mtprocHandler.obj $(TOPDIR)\examples\mtproc\implementation.obj $(TOPDIR)\examples\mtproc\dispatcher.obj
#mtprocHandler.exe: mtprocHandler.obj $(MTPROC_GTEST_OBJS) $(TOPDIR)\src\libwolframe.lib

local_all:

local_clean:
	@-erase test.bat logTest.log 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo PATH=%PATH%;$(BOOST_DIR)\Lib >> test.bat
	@-echo testNamedRetVal >> test.bat
	@-echo logTest >> test.bat
	@-echo versionTest >> test.bat
	@-echo counterTest >> test.bat
# broken on windows: gives wrong path canonization results
	@-echo resolvePathTest >> test.bat
	@-echo singletonTest >> test.bat
	@-echo poolTest >> test.bat
	@-echo protocolArgumentParsing >> test.bat
# broken on windows
#	@-echo pechoHandler >> test.bat
#	@-echo mtprocHandler >> test.bat
	@echo
	@-test.bat
