TOPDIR = ..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CPPFLAGS = \
	/D_WIN32_WINNT=0x403

INCLUDE_DIRS = \
	/I$(TOPDIR)/include /I. \
	/I$(TOPDIR)/src \
	/I"$(BOOST_DIR)" \
	/I"$(PLATFORM_SDK_DIR)\Include"

# Note: libraries are picked automatically on Windows!
SDK_LDFLAGS = /LIBPATH:"$(PLATFORM_SDK_DIR)\lib"
INCLUDE_LDFLAGS = \
	$(SDK_LDFLAGS) $(BOOST_LDFLAGS)

# Gtest

INCLUDE_LIBS = \
	Advapi32.lib

!IFDEF WITH_GTEST

INCLUDE_DIRS = \
	$(INCLUDE_DIRS)	/I"$(GTEST_INCLUDE_DIRS)"

INCLUDE_LDFLAGS = \
	$(INCLUDE_LDFLAGS) /LIBPATH:"$(GTEST_LIB_DIR)"

INCLUDE_LIBS = \
	$(INCLUDE_LIBS) $(GTEST_LIBS)
!ENDIF

TEST_CPP_BINS = \
	logTest.exe \
	poolTest.exe

# currently don't compile because of ref-to-ptr trickery in test template
#	pechoHandlerTest.exe
#	xmlselectHandlerTest.exe

!IFDEF WITH_GTEST
TEST_CPP_BINS = \
	$(TEST_CPP_BINS) \
	versionTest.exe \
	counterTest.exe
# currently don't compile because of ref-to-ptr trickery in test template
#	pechoHandler-gTest$(EXE)
!ENDIF

OBJS = \

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

logTest.exe: logTest.obj $(TOPDIR)\src\smerp.lib
pechoHandlerTest.exe: pechoHandlerTest.obj $(TOPDIR)\src\pechoHandler.o
xmlselectHandlerTest.exe: xmlselectHandlerTest.obj $(TOPDIR)\src\xmlselectHandler.o
!IFDEF WITH_GTEST
versionTest.exe: versionTest.obj $(TOPDIR)\src\smerp.lib
counterTest.exe: counterTest.obj $(TOPDIR)\src\smerp.lib
poolTest.exe: poolTest.obj $(TOPDIR)\src\smerp.lib
!ENDIF

local_all:

local_clean:
	@-erase test.bat logTest.log 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo PATH=%PATH%;$(BOOST_DIR)\Lib >> test.bat
!IFDEF WITH_GTEST
	@-echo logTest >> test.bat
	@-echo echo Testing version... >> test.bat
	@-echo versionTest >> test.bat
	@-echo echo Testing counter.. >> test.bat
	@-echo counterTest >> test.bat
	@-echo poolTest >> test.bat
!ENDIF
	@-test.bat
