TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

# PostgreSQL
!IFDEF WITH_PGSQL
SUBDIRS = \
	$(SUBDIRS) PostgreSQL
!ENDIF

# Oracle
!IFDEF WITH_ORACLE
SUBDIRS = \
	$(SUBDIRS) Oracle
!ENDIF

# sqlite3
!IFDEF WITH_SQLITE3
SUBDIRS = \
	$(SUBDIRS) SQLite3
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
