TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I$(TOPDIR)/lua/src

INCLUDE_LIBS = \
	$(TOPDIR)\lua\src\lua.lib

DYNAMIC_MODULE = \
	c-testmod.dll

OBJS = \
	c-testmod.obj
	
all: $(DYNAMIC_MODULE)

test: $(DYNAMIC_MODULE) local_test

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(OBJS)
	$(LINK) /dll /nologo /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo $(TOPDIR)\lua\src\lua.exe test.lua World 47 3.1415 >> test.bat
	@-test.bat
