TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\src\modules\database\sqlite3 \
	/I$(TOPDIR)\gtest\include \
	/I"$(TOPDIR)\sqlite3"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\gtest\gtest-all.obj \
	$(TOPDIR)\src\modules\database\sqlite3\SQLite.obj \
	$(TOPDIR)\sqlite3\sqlite3.lib \
	$(TOPDIR)\src\modules\database\dbTransaction.obj \
	kernel32.lib advapi32.lib Ws2_32.lib

TEST_CPP_BINS = \
	sqliteUnit.exe

sqliteUnit.exe: sqliteUnit.obj

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat

