TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\src\modules\database\sqlite3 \
	/I$(TOPDIR)\gtest\include \
	/I"$(TOPDIR)\sqlite3"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\gtest\gtest-all.obj \
	$(TOPDIR)\sqlite3\sqlite3.lib \
	kernel32.lib advapi32.lib Ws2_32.lib

TEST_CPP_OBJS = \
	sqliteModuleFiles.obj

TEST_CPP_BINS = \
	sqliteUnit.exe

sqliteUnit.exe: sqliteUnit.obj

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:
	@-erase test.db garbage.db 2>NUL

local_distclean:

local_test: $(TEST_CPP_BINS)
	@-erase test.db garbage.db 2>NUL
	@-copy Makefile.W32 garbage.db
	@$(SQLITE3) test.db < testDB.sql
	@-sqliteUnit

# Aba: on Windows?
#	@dd if=/dev/urandom of=garbage.db bs=4096 count=1

