TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\src\modules\database\sqlite3 \
	/I$(TOPDIR)\3rdParty\gtest\include \
	/I$(TOPDIR)\wtest\include \
	/I"$(TOPDIR)\3rdParty\sqlite3"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\3rdParty\gtest\gtest-all.obj \
	$(TOPDIR)\wtest\wtest.lib \
	$(TOPDIR)\3rdParty\sqlite3\sqlite3.lib \
	kernel32.lib advapi32.lib Ws2_32.lib \
	$(TOPDIR)\src\libwfsingleton\wfsingleton.lib

CPP_OBJS = \
	sqliteModuleFiles.obj

CPP_BINS = \
	sqliteUnit.exe \
	createRandom.exe

sqliteUnit.exe: sqliteUnit.obj sqliteModuleFiles.obj
createRandom.exe: createRandom.obj

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:
	@-erase test.db garbage.db 2>NUL

local_distclean:

test.db:
	$(TOPDIR)\3rdParty\sqlite3\sqlite3.exe test.db < testDB.sql

garbage.db:
	createRandom 4096 garbage.db

local_test: $(TEST_CPP_BINS) test.db garbage.db
	@-copy $(TOPDIR)\src\libwfsingleton\wfsingleton.dll .
	@-sqliteUnit
