TOPDIR = ..\..\..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR) \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\src \
	/I"$(BOOST_INCLUDE_DIR)"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwfsingleton\wfsingleton.lib \
	kernel32.lib advapi32.lib Ws2_32.lib

DYNAMIC_MODULE = \
	mod_filter_testtoken.dll

CPP_OBJS = \
	testtoken_filter.obj \
	mod_filter_testtoken.obj

all: $(DYNAMIC_MODULE)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(CPP_OBJS)
	$(LINK) /dll /def:TestTokenFilter.def /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:

local_distclean:

local_test:

