TOPDIR = ../..

SUBDIRS = CommandHandlerModule DoctypeDetectionModule FilterModule FormFunctionModule ProgramTypeModule DDLCompilerModule CustomDataTypeModule NormalizerModule RuntimeEnvironmentModule AuthenticatorModule DatabaseModule

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
