TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

SUBDIRS = \
	$(SUBDIRS) directmap

!IFDEF WITH_LUA
SUBDIRS = \
	$(SUBDIRS) lua
!ENDIF

!IFDEF WITH_PYTHON
SUBDIRS = \
	$(SUBDIRS) python
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
