TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

!IFDEF WITH_LUA
SUBDIRS = \
	$(SUBDIRS) luaCommandHandler
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
