TOPDIR = ../../../..

SUBDIRS =

-include $(TOPDIR)/makefiles/gmake/platform.mk

INCLUDE_DIRS =

INCLUDE_CXXFLAGS =

INCLUDE_LDFLAGS =

INCLUDE_LIBS =

DYNAMIC_MODULE = \
	not_a_mod.so

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_install:

local_uninstall:

local_test:

