TOPDIR = ../../../..

-include $(TOPDIR)/makefiles/gmake/platform.mk

SUBDIRS = testtoken

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
