TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CFLAGS = \
	/D_WIN32_WINNT=0x504 \
	/wd4146 /wd4244

INCLUDE_DIRS = \
	/I$(TOPDIR)\libgmp \
	/I$(TOPDIR)/lua/src

INCLUDE_LIBS = \
	$(TOPDIR)\libgmp\mpn\mpn.lib \
	$(TOPDIR)\libgmp\mpz\mpz.lib \
	$(TOPDIR)\libgmp\mpq\mpq.lib \
	$(TOPDIR)\libgmp\mpf\mpf.lib \
	$(TOPDIR)\libgmp\gmpcommon.lib \
	$(TOPDIR)\libgmp\printf\printf.lib \
	$(TOPDIR)\libgmp\scanf\scanf.lib \
	$(TOPDIR)\lua\src\lua.lib

DYNAMIC_MODULE = \
	c-gmp.dll

OBJS = \
	lgmp.obj
	
all: $(DYNAMIC_MODULE)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(OBJS)
	$(LINK) /dll /nologo /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo $(TOPDIR)\lua\src\lua.exe test.lua 4 5 >> test.bat
	@-echo $(TOPDIR)\lua\src\lua.exe test.lua 424234238490238409238402380482304 52342342342342342342342323 >> test.bat
	@-test.bat
