TOPDIR = ../../..

SUBDIRS = mod_test mod_test_containers not_a_mod missing_symbol

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
