TOPDIR = ..\..\..

SUBDIRS = mod_test mod_test_containers not_a_mod libbla missing_symbol resolvable_symbol

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
