#!/usr/bin/expect
#
# Start a wolframe daemon and communicate with it
#

package require Expect

set config pecho.conf

set timeout 3
set serverpid [spawn ./pechod -c $config -f]

puts "wolframe echo with protocol started with configuration file: $config (pid: $serverpid)"
# allow the server to start
sleep 2

set timeout 3
if { [catch {
	spawn telnet localhost 7661

	expect 	{
		timeout	{ return "--> oops. timeout occured waiting for server banner\n" }
		eof	{ return "--> EOF waiting for server banner: that's bad\n" }
		"OK expecting command\r"	{ send_user " --> Connected.\n" }
	}

	set message "1 short line"
	send "$message\r"
	expect "BAD unknown command\r"
	expect "OK expecting command\r"

	send "echo tolower\r"
	expect "OK enter data"
	set message "2nd Short Line With üèöéäà°§"
	send "$message\r.\r"
	expect "$message\r"

	set timeout 1
	send "quit\r"
	expect "Thanks for using Wolframe."
	expect 	{
		timeout	{ send_user " --> oops. timeout occured\n"; return 1 }
		eof	{ send_user " --> Connection closed. OK\n" }
	}
} reason] } {
	send_user "Error: $reason\n"
	exit 1
}
