TOPDIR = ../../../..

SUBDIRS =

-include $(TOPDIR)/makefiles/gmake/platform.mk

NOINST_DYNAMIC_LIB = libbla.so
NOINST_DYNAMIC_LIB_MAJOR = 0
NOINST_DYNAMIC_LIB_MINOR = 0
NOINST_DYNAMIC_LIB_PATCH = 0

CPP_OBJS = \
	bla.o

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_install:

local_test:
