TOPDIR = ..\..\..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\src\modules\database\postgresql \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I"$(PGSQL_DIR)\include"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwfsingleton\wfsingleton.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\src\libwolframe_serialize\wolframe_serialize.lib \
	$(TOPDIR)\src\libwolframe_langbind\wolframe_langbind.lib \
	"$(PGSQL_DIR)\lib\libpq.lib" \
	kernel32.lib advapi32.lib Ws2_32.lib

DYNAMIC_MODULE = \
	mod_db_postgresqltest.dll

CPP_OBJS = \
	PostgreSQLTest.obj \
	PostgreSQLModuleFiles.obj \
	mod_db_postgresqltest.obj

all: $(DYNAMIC_MODULE)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(CPP_OBJS)
	$(LINK) /dll /def:PostgreSQLTestModule.def /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:
	@-erase $(DYNAMIC_MODULE) 2>NUL
	@-erase $(CPP_OBJS) 2>NUL

local_distclean:

local_test:
