#include "PostgreSQLconfig.cpp"
#include "PostgreSQLconstructor.cpp"
#include "PostgreSQL.cpp"
#include "PostgreSQLprogram.cpp"
#include "PostgreSQLtransactionExecStatemachine.cpp"
#include "PostgreSQLsubstitutingStatement.cpp"
#include "PostgreSQLstatement.cpp"
