TOPDIR = ../../../..

SUBDIRS = fakegraphix audit

-include $(TOPDIR)/makefiles/gmake/platform.mk

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
