//
// global.hpp
//

#ifndef _GLOBAL_HPP_INCLUDED
#define _GLOBAL_HPP_INCLUDED

#define ORGANIZATION_NAME "Wolframe"
#define ORGANIZATION_DOMAIN "wolframe.org"
#define APPLICATION_NAME "qtclient"

#define DEFAULT_UI_FORMS_DIR "."
#define DEFAULT_UI_FORM_TRANSLATIONS_DIR "."
#define DEFAULT_UI_FORM_RESOURCES_DIR "."

#define DEFAULT_DATA_LOADER_DIR "."

#define RESTART_CODE 1000

#define DEFAULT_LOCALE "en_US"

#define SYSTEM_LANGUAGE "SYSTEM"

#define WOLFRAME_VERSION "0.0.1"

#define DEFAULT_UILOADMODE LocalFile
#define DEFAULT_DATALOADMODE Network
#define DEFAULT_UILOADMODE_STRING "LocalFile"
#define DEFAULT_DATALOADMODE_STRING "Network"

#endif // _GLOBAL_HPP_INCLUDED
