TOPDIR = ..\..\..\..

SUBDIRS = functions

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

I18NS = \
	i18n\init.de_CH.qm \
	i18n\init.ro_RO.qm \
	i18n\form1.de_CH.qm \
	i18n\form1.ro_RO.qm \
	i18n\form2.de_CH.qm \
	i18n\form2.ro_RO.qm \
	i18n\form3.de_CH.qm \
	i18n\form3.ro_RO.qm \
	i18n\form4.de_CH.qm \
	i18n\form4.ro_RO.qm \
	i18n\form5.de_CH.qm \
	i18n\form5.ro_RO.qm \
	i18n\form5_create.de_CH.qm \
	i18n\form5_create.ro_RO.qm \
	i18n\form5_update.de_CH.qm \
	i18n\form5_update.ro_RO.qm \
	i18n\form5_show.de_CH.qm \
	i18n\form5_show.ro_RO.qm

RESOURCES = \
	resources\testcases.rcc

i18n\init.de_CH.qm: i18n\init.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\init.de_CH.ts -qm i18n\init.de_CH.qm

i18n\init.ro_RO.qm: i18n\init.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\init.ro_RO.ts -qm i18n\init.ro_RO.qm

i18n\form1.de_CH.qm: i18n\form1.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form1.de_CH.ts -qm i18n\form1.de_CH.qm

i18n\form1.ro_RO.qm: i18n\form1.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form1.ro_RO.ts -qm i18n\form1.ro_RO.qm

i18n\form2.de_CH.qm: i18n\form2.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form2.de_CH.ts -qm i18n\form2.de_CH.qm

i18n\form2.ro_RO.qm: i18n\form2.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form2.ro_RO.ts -qm i18n\form2.ro_RO.qm

i18n\form3.de_CH.qm: i18n\form3.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form3.de_CH.ts -qm i18n\form3.de_CH.qm

i18n\form3.ro_RO.qm: i18n\form3.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form3.ro_RO.ts -qm i18n\form3.ro_RO.qm

i18n\form4.de_CH.qm: i18n\form4.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form4.de_CH.ts -qm i18n\form4.de_CH.qm

i18n\form4.ro_RO.qm: i18n\form4.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form4.ro_RO.ts -qm i18n\form4.ro_RO.qm

i18n\form5.de_CH.qm: i18n\form5.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5.de_CH.ts -qm i18n\form5.de_CH.qm

i18n\form5.ro_RO.qm: i18n\form5.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5.ro_RO.ts -qm i18n\form5.ro_RO.qm

i18n\form5_create.de_CH.qm: i18n\form5_create.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_create.de_CH.ts -qm i18n\form5_create.de_CH.qm

i18n\form5_create.ro_RO.qm: i18n\form5_create.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_create.ro_RO.ts -qm i18n\form5_create.ro_RO.qm

i18n\form5_update.de_CH.qm: i18n\form5_update.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_update.de_CH.ts -qm i18n\form5_update.de_CH.qm

i18n\form5_update.ro_RO.qm: i18n\form5_update.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_update.ro_RO.ts -qm i18n\form5_update.ro_RO.qm

i18n\form5_show.de_CH.qm: i18n\form5_show.de_CH.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_show.de_CH.ts -qm i18n\form5_show.de_CH.qm

i18n\form5_show.ro_RO.qm: i18n\form5_show.ro_RO.ts
	$(QT_DIR)\bin\lrelease.exe i18n\form5_show.ro_RO.ts -qm i18n\form5_show.ro_RO.qm

resources\testcases.rcc: resources\testcases.qrc
	$(QT_DIR)\bin\rcc.exe -binary resources\testcases.qrc -o resources\testcases.rcc
	
local_all: $(I18NS) $(RESOURCES)

local_clean:
	@-erase $(I18NS) 2>NUL
	@-erase $(UIS) 2>NUL

local_distclean:

local_test:

buildi18n:
	$(QT_DIR)\bin\lupdate.exe forms\init.ui -ts i18n\init.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\init.ui -ts i18n\init.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form1.ui -ts i18n\form1.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form1.ui -ts i18n\form1.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form2.ui -ts i18n\form2.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form2.ui -ts i18n\form2.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form3.ui -ts i18n\form3.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form3.ui -ts i18n\form3.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form4.ui -ts i18n\form4.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form4.ui -ts i18n\form4.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5.ui -ts i18n\form5.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5.ui -ts i18n\form5.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_create.ui -ts i18n\form5_create.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_create.ui -ts i18n\form5_create.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_update.ui -ts i18n\form5_update.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_update.ui -ts i18n\form5_update.ro_RO.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_show.ui -ts i18n\form5_show.de_CH.ts
	$(QT_DIR)\bin\lupdate.exe forms\form5_show.ui -ts i18n\form5_show.ro_RO.ts
