TOPDIR = ../../../..

ifeq ($(WITH_LIBHPDF),1)
ifeq ($(WITH_TEXTWOLF),1)
SUBDIRS += fakepdfprint
endif
endif

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

local_install:

local_uninstall:
