#!/usr/bin/expect
#
# Start a wolframe daemon and check the configuration
#
# Arguments:
#     configuration file
#     wolframed return code
#     error / warning / ok message
#

if { [llength $argv] != 3 } {
    puts "usage: checkConfig <config file> <return code> <error / warning / ok message>"
    exit 1
}

set config [lindex $argv 0]		;# 1st script argument
set retval [lindex $argv 1]		;# 2nd script argument
set outmsg [lindex $argv 2]		;# 3rd script argument

# puts "Configuration file: $config, expecting exit code $retval and message \"$outmsg\""

set timeout 3
spawn ../../src/wolframed -c $config -t

expect 	{
	timeout		{ send_user "Process timed out.\n" }
#	"$outmsg\r"	{ puts "Got expected message in: $expect_out(buffer)\n" }
	"$outmsg\r"	{ puts "Got expected message: $expect_out(0,string)\n" }
	eof		{ puts "Got EOF before the expected message.\n" }
}

catch wait reason
set procid [lindex $reason 0]
if { [lindex $reason 2] == 0 } {
    set retval [lindex $reason 3]
    puts "Pid $procid return code: $retval\n"
} else {
    puts "Pid $procid, some execution error occured. wait returned $reason\n"
}
