TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. /I"$(LIBXML2_DIR)\include" \
	/I"$(LIBXML2_DIR)\include\libxml2" \
	/I"$(WIN_ICONV_DIR)"

# Note: libraries are picked automatically on Windows!
INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	"$(LIBXML2_DIR)\lib\libxml2.lib"

TEST_CPP_BINS = \
	testlibxml2.exe

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testlibxml2.exe: testlibxml2.obj

local_all:

local_clean:
	@-erase test.bat 2>NUL
	@-erase *.RES 2>NUL
	@-erase *.DIFF 2>NUL

local_distclean:

ENCODINGS=UTF-8 UCS-2LE UCS-2BE UTF-16LE UTF-16BE

local_test:
	@-echo @echo off > test.bat
	@-echo copy "$(LIBXML2_DIR)\bin\libxml2.dll" . >> test.bat
	@-echo copy "$(WIN_ICONV_DIR)\iconv.dll" . >> test.bat
	@for %%e IN ( $(ENCODINGS) ) do \
		@echo echo Testing libxml2 with encoding %%e >> test.bat & \
		echo testlibxml2 test-%%e.xml ^> %%e.RES >> test.bat & \
		echo fc %%e.MUST %%e.RES ^> %%e.DIFF >> test.bat
	@-test.bat
