TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. /I"$(LIBXML2_DIR)\include" \
	/I"$(LIBXML2_DIR)\include\libxml" \
	/I"$(WIN_ICONV_DIR)"

# Note: libraries are picked automatically on Windows!
INCLUDE_LDFLAGS = \
	$(SDK_LDFLAGS) $(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	"$(LIBXML2_DIR)\lib\libxml2.lib"

TEST_CPP_BINS = \
	testlibxml2.exe

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testlibxml2.exe: testlibxml2.obj

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo copy "$(LIBXML2_DIR)\lib\libxml2.dll" . >> test.bat
	@-echo copy "$(WIN_ICONV_DIR)\iconv.dll" . >> test.bat
	@-echo UTF8
	@-echo testlibxml2 test-UTF8.xml >> test.bat
	@-echo UCS2BE
	@-echo testlibxml2 test-UCS-2BE.xml >> test.bat
	@-echo UCS2LE
	@-echo testlibxml2 test-UCS-2LE.xml >> test.bat
	@-echo UTF16BE
	@-echo testlibxml2 test-UTF-16BE.xml >> test.bat
	@-echo UTF16LE
	@-echo testlibxml2 test-UTF-16LE.xml >> test.bat
	@-test.bat
