TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CPPFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. /I"$(LIBXML2_DIR)\include" \
	/I"$(LIBXML2_DIR)\include\libxml" \
	/I"$(ICONV_DIR)\include"

# Note: libraries are picked automatically on Windows!
SDK_LDFLAGS = /LIBPATH:"$(PLATFORM_SDK_DIR)\lib"
INCLUDE_LDFLAGS = \
	$(SDK_LDFLAGS) $(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	"$(LIBXML2_DIR)\lib\libxml2.lib"

TEST_CPP_BINS = \
	testlibxml1.exe

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testlibxml1.exe: testlibxml1.obj

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo copy "$(LIBXML2_DIR)\bin\libxml2.dll" . >> test.bat
	@-echo copy "$(ICONV_DIR)\bin\iconv.dll" . >> test.bat
	@-echo copy "$(ZLIB_DIR)\bin\zlib1.dll" . >> test.bat
	@-echo testlibxml1 test.xml >> test.bat
	@-test.bat
