Document: smerp
Title: Debian smerp Manual
Author: <insert document author here>
Abstract: This manual describes what smerp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smerp/smerp.sgml.gz

Format: postscript
Files: /usr/share/doc/smerp/smerp.ps.gz

Format: text
Files: /usr/share/doc/smerp/smerp.text.gz

Format: HTML
Index: /usr/share/doc/smerp/html/index.html
Files: /usr/share/doc/smerp/html/*.html
