Document: wolframe
Title: Debian wolframe Manual
Author: <insert document author here>
Abstract: This manual describes what wolframe is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wolframe/wolframe.sgml.gz

Format: postscript
Files: /usr/share/doc/wolframe/wolframe.ps.gz

Format: text
Files: /usr/share/doc/wolframe/wolframe.text.gz

Format: HTML
Index: /usr/share/doc/wolframe/html/index.html
Files: /usr/share/doc/wolframe/html/*.html
