TOPDIR = ..

SUBDIRS = echo pecho

!IFDEF WITH_LUA
SUBDIRS = \
	$(SUBDIRS) lua
# pf:disabled temporarily: iproc
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
