TOPDIR = ..

SUBDIRS = echo pecho
# mtproc breaks on Windows

!IFDEF WITH_LUA
SUBDIRS = \
	$(SUBDIRS) lua
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
