TOPDIR = ..\..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\src \
	/I$(TOPDIR)\tests \
	/I"$(BOOST_INCLUDE_DIR)"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe_serialize\wolframe_serialize.lib \
	$(TOPDIR)\src\libwolframe_langbind\wolframe_langbind.lib \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	kernel32.lib advapi32.lib Ws2_32.lib

DYNAMIC_MODULE = \
	mod_graphix.dll

CPP_OBJS = \
	mod_graphix.obj

all: $(DYNAMIC_MODULE)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(CPP_OBJS)
	$(LINK) /dll /def:mod_graphix.def /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:

local_distclean:

local_test:
