#!/usr/bin/expect
#
# Start a wolframe daemon and communicate with it
#

package require Expect

set config wolframe.conf

set timeout 5
set serverpid [spawn ../../src/wolframed -c $config -f]

puts "wolframe daemon started with configuration file: $config (pid: $serverpid)"
# allow the server to start
sleep 5

set timeout 5
if { [catch {
	spawn ./wolframec 127.0.0.1 7661

	expect 	{
		timeout	{ return "--> oops. timeout occured waiting for server banner\n" }
		eof	{ return "--> EOF waiting for server banner: that's bad\n" }
		"state 'authorized'\r"	{ send_user " --> Connected.\n" }
	}
} reason] } {
	send_user "Error: $reason\n"
	exit 1
}
