TOPDIR = ..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I.

INCLUDE_LIBS =

OBJS = \
	cJSON.obj

STATIC_LIB = \
	cjson.lib

LIBRARIES = \
	$(STATIC_LIB)
	
BINS = \
	lua.exe
	
!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

cjson.lib: $(OBJS)
	$(LINK) /lib /out:$@ $(STATIC_LDFLAGS) $(LIBS) $?

local_all: $(LIBRARIES) $(BINS)

local_clean:

local_distclean:

local_test:
