TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504
	
INCLUDE_DIRS = \
	/I. \
	/Iinclude \
	/I"$(PLATFORM_SDK_DIR)\Include" 

INCLUDE_LIBS =

OBJS = \
	strptime.obj 

LIBRARIES = \
	plibc.lib
	
!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

plibc.lib: $(OBJS)
	$(LINK) /lib /out:$@ $(STATIC_LDFLAGS) $?

local_all: $(LIBRARIES)

local_clean:

local_distclean:

local_test:
