TOPDIR = ../../..

SUBDIRS =

-include $(TOPDIR)/makefiles/gmake/platform.mk

SUBDIRS += textwolf token char line

# libxml2
#ifeq ($(WITH_LIBXML2),1)
#SUBDIRS += libxml2
#endif

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_distclean:

local_test:

