TOPDIR = ..\..\..

SUBDIRS = textwolf token char blob line

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

# libxml2
!IFDEF WITH_LIBXML2
SUBDIRS = \
	$(SUBDIRS) libxml2
!ENDIF

# rapidjson
!IFDEF WITH_CJSON
SUBDIRS = \
	$(SUBDIRS) cjson
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
