TOPDIR = ..\..\..

SUBDIRS = blob

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

# textwolf
!IFDEF WITH_TEXTWOLF
SUBDIRS = \
	$(SUBDIRS) textwolf token char line
!ENDIF

# libxml2
!IFDEF WITH_LIBXML2
SUBDIRS = \
	$(SUBDIRS) libxml2
!ENDIF

# cjson
!IFDEF WITH_CJSON
SUBDIRS = \
	$(SUBDIRS) cjson
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
