CREATE TABLESPACE wolframe_TS
	DATAFILE '/db/oracle/oradata/orcl/wolframe.dat' SIZE 10M REUSE AUTOEXTEND ON NEXT 50M
	MAXSIZE 2000M
	DEFAULT STORAGE (
		INITIAL		1M
		NEXT		1M
		PCTINCREASE	0
		MINEXTENTS	1
		MAXEXTENTS	UNLIMITED
	)
;

CREATE USER wolfusr IDENTIFIED BY wolfpwd
	DEFAULT TABLESPACE wolframe_TS
	TEMPORARY TABLESPACE temp
	QUOTA UNLIMITED ON wolframe_TS
	ACCOUNT UNLOCK
;

GRANT CONNECT, RESOURCE TO wolfusr;
