#!/bin/sh

res=`find ../../wolfilter/modules ../../../src/modules -name "*$1.so" | sed 's@^../@./@' | sed 's/.so$//' | head -n1 -`
if [ x"$res" = "x" ]; then
	res=`find ../../wolfilter/modules ../../../src/modules -name "*$1.cpp" | sed 's@^../@./@' | sed 's/.cpp$//' | head -n1 -`
	if [ x"$res" = "x" ]; then
		res="NOTFOUND:$1"
	fi
fi
echo $res
