TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

configTest: $(TOPDIR)/src/wolframed

local_all:

local_clean:

local_distclean:

local_test:
	@-$(EXPECT) testEcho
