TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

configTest: $(TOPDIR)\src\wolframed.exe

local_all:

local_clean:

local_distclean:

local_test:
#	@-"$(EXPECT)" testEcho.ex
#	@-"$(EXPECT)" testPEcho.ex
