#!/usr/bin/expect
#
# Start a wolframe daemon and communicate with it
#

package require Expect

set config wolframe.conf

set timeout 3
set serverpid [spawn ../../src/wolframed -c $config -f]

puts "wolframed started with configuration file: $config (pid: $serverpid)"
# allow the server to start
sleep 2

set timeout 3
spawn telnet localhost 7661

expect 	{
	timeout	{ send_user " --> oops. timeout occured waiting for server banner\n" }
	eof	{ send_user " --> EOF waiting for server banner: that's bad\n" }
	"OK.\r"	{ send_user " --> Connected.\n" }
}

set message "1 short line"
send "$message\r"
expect "$message"

set message "2nd short line with üèöéäà°§"
send "$message\r"
expect "$message"

set timeout 1
send "quit\r"
expect "Bye."
expect 	{
	timeout	{ send_user " --> oops. timeout occured\n" }
	eof	{ send_user " --> Connection closed. OK\n" }
}
