#!/usr/bin/expect
#
# Checks an authentication method
#

package require Expect
source md5.tcl

set timeout 5
log_user 0

puts -nonewline "Authentication SASL CRAM MD5 wrong password - "

spawn ./authTest SASL

expect "Choose a SASL mech:"
send "CRAM-MD5\r"
expect "SASL data: "
send "\r"
expect -re "Got SASL data: (<.*>)"

set challenge $expect_out(1,string)
set user "test"
set password "xxx"
set reply [md5::hmac $password $challenge]
set answer "$user $reply"
send "$answer\r"

expect {
	"Authentication succeeded!"	{ puts "ERROR" }
	"Authentication failed!"	{ puts "OK" }
	timeout 			{ puts "Timeout" }
}
