#!/usr/bin/expect
#
# Checks an authentication method
#

package require Expect

set timeout 2
log_user 0

puts -nonewline "Authentication SASL LOGIN unknown user - "

spawn ./authTest SASL

expect "Choose a SASL mech:"
send "LOGIN\r"
expect "SASL data: "
# no initial client data, server will ask for it
send "\r"
expect "Got SASL data: Username:"
# perl -MMIME::Base64 -e 'print encode_base64("test2");'
send "dGVzdDI=\r"
expect "Got SASL data: Password:"
# perl -MMIME::Base64 -e 'print encode_base64("xx");'
send "eHg=\r"

expect {
	"Authentication succeeded!"	{ puts "ERROR" }
	"Authentication failed!"	{ puts "OK" }
	timeout 			{ puts "Timeout" }
}
