#!/usr/bin/expect
#
# Checks an authentication method
#

package require Expect

set timeout 2
#log_user 0

puts -nonewline "Authentication SASL CRAM MD5 successfull - "

spawn ./authTest SASL

expect "Choose a SASL mech:"
send "CRAM-MD5\r"
expect "SASL data: "
# perl -MMIME::Base64 -e 'print encode_base64("test@blabla.com");'
send "\004"

expect {
	"Authentication succeeded!"	{ puts "OK" }
	"Authentication failed!"	{ puts "ERROR" }
	timeout 			{ puts "Timeout" }
}
