#!/usr/bin/expect
#
# Checks an authentication method
#

set timeout 1
log_user 0

puts -nonewline "Authentication TEXT_FILE failed - "

spawn ./authTest TEXT_FILE

expect "login: "
send "test\r"
expect "Enter your password:"
send "xx\r"
expect {
	"Authentication succeeded!"	{ puts "OK" }
	"Authentication failed!"	{ puts "ERROR" }
	timeout 			{ puts "Timeout" }
}
