#!/usr/bin/expect
#
# Checks an authentication method
#

package require Expect

set timeout 2
log_user 0

puts -nonewline "Authentication SASL PLAIN wrong password - "

spawn ./authTest SASL

expect "Choose a SASL mech:"
send "PLAIN\r"
expect "SASL data: "
# perl -MMIME::Base64 -e 'print encode_base64("test\0test\0x");'
send "dGVzdAB0ZXN0AHg=\r"

expect {
	"Authentication succeeded!"	{ puts "ERROR" }
	"Authentication failed!"	{ puts "OK" }
	timeout 			{ puts "Timeout" }
}
