TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\src \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\3rdParty\gtest\include \
	/I$(TOPDIR)\src\modules\authentication\textfile \
	/I$(TOPDIR)\src\modules\authentication\database

# Note: libraries are picked automatically on Windows!
INCLUDE_LDFLAGS = \
	/LIBPATH:$(TOPDIR)\src\libwfshared \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	Advapi32.lib Ws2_32.lib \
	$(TOPDIR)\3rdParty\gtest\gtest-all.obj \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	wfshared.lib

CPP_OBJS = \
	$(TOPDIR)\src\modules\authentication\textfile\TextFileAuth.obj \
	$(TOPDIR)\src\modules\authentication\database\DBauth.obj \
	$(TOPDIR)\src\modules\authentication\textfile\passwdFile.obj

TEST_CPP_BINS = \
	authenticationTest.exe \
	passwdFileTest.exe \
	textFileTest.exe


!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

authenticationTest.exe: authenticationTest.obj $(CPP_OBJS) $(TOPDIR)\src\wolframe.lib
textFileTest.exe: textFileTest.obj $(CPP_OBJS) $(TOPDIR)\src\wolframe.lib
passwdFileTest.exe: passwdFileTest.obj $(CPP_OBJS)


local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo PATH=%PATH%;$(BOOST_DIR)\Lib >> test.bat
	@-echo authenticationTest >> test.bat
	@-echo passwdFileTest >> test.bat
	@-echo textFileTest >> test.bat
	@-echo echo off >> test.bat
	@-test.bat
