TOPDIR = ..\..\..

SUBDIRS = testPdfPrinter

!IFDEF WITH_LIBHPDF
!IFDEF WITH_TEXTWOLF
SUBDIRS = \
	$(SUBDIRS) haruPdfPrinter
!ENDIF
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
