TOPDIR = ../..

SUBDIRS =

!IFDEF WITH_LIBGMP
SUBDIRS = \
	$(SUBDIRS) libgmp
!ENDIF

!IFDEF WITH_MPFR
SUBDIRS = \
	$(SUBDIRS) mpfr
!ENDIF

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:
