#!/bin/sh
#************************************************************************
#
# Copyright (C) 2011 - 2014 Project Wolframe.
# All rights reserved.
#
# This file is part of Project Wolframe.
#
# Commercial Usage
#    Licensees holding valid Project Wolframe Commercial licenses may
#    use this file in accordance with the Project Wolframe
#    Commercial License Agreement provided with the Software or,
#    alternatively, in accordance with the terms contained
#    in a written agreement between the licensee and Project Wolframe.
#
# GNU General Public License Usage
#    Alternatively, you can redistribute this file and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Wolframe is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Wolframe.  If not, see <http://www.gnu.org/licenses/>.
#
# If you have questions regarding the use of this file, please contact
# Project Wolframe.
#
#************************************************************************/

echo "//****************************************************************"
echo "// This file has been generated by $0"
echo "// DO NOT EDIT THIS FILE !"
echo "//****************************************************************"

echo 'struct HexNumFactor'
echo '{'
echo '	enum {TabSize=20};'
echo '	unsigned int ofs;'
echo '	unsigned char tab[TabSize];'
echo '};'
echo 'enum {MaxDecDigits=40};'
echo 'static HexNumFactor g_decnum_hexnum_factor_table[40] = {'
DECNUM='1'
loopcnt=0
while [ $loopcnt -lt 40 ]
do
	loopcnt=`expr $loopcnt + 1`

	HEXNUM=`echo "obase=16; $DECNUM" | bc`
	DECNUM="$DECNUM"0

	nof_digits=`echo "$HEXNUM" | wc -c`
	nof_leading_zeros=`expr 40 - $nof_digits`
	ii=0
	NUMPREFIX='0'
	while [ $ii -lt $nof_leading_zeros ]
	do
		NUMPREFIX="0$NUMPREFIX"
		ii=`expr $ii + 1`
	done
	OFFSET=`expr $nof_leading_zeros / 2`
	TAB=`echo "$NUMPREFIX$HEXNUM" | sed "s/\([0-9A-F][0-9A-F]\)/0x\1,/g" | sed 's/,$/}/' | sed 's/^/{/'`

	if [ $loopcnt -lt 40 ]; then
		echo "{$OFFSET,$TAB},"
	else
		echo "{$OFFSET,$TAB}"
	fi
done
echo '};';
echo
echo


