TOPDIR = ..\..\..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)"

INCLUDE_LDFLAGS = \
	/LIBPATH:$(TOPDIR)\src\libwfsingleton \
	$(BOOST_LDFLAGS)

# Aba: wolframe_serialize and wolframe_langbind are still needed,
# getting link errors otherwise..
INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\src\libwolframe_serialize\wolframe_serialize.lib \
	$(TOPDIR)\src\libwolframe_langbind\wolframe_langbind.lib \
	kernel32.lib advapi32.lib Ws2_32.lib \
	wfsingleton.lib

DYNAMIC_MODULE = \
	mod_db_testtrace.dll

CPP_OBJS = \
	testtraceDatabase.obj \
	testtraceTransaction.obj \
	mod_db_testtrace.obj

all: $(DYNAMIC_MODULE)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

$(DYNAMIC_MODULE): $(CPP_OBJS)
	$(LINK) /dll /def:TesttraceDatabaseModule.def /out:$@ $(LDFLAGS) $(LIBS) $?

local_all:

local_clean:
	@-erase $(DYNAMIC_MODULE) 2>NUL
	@-erase $(CPP_OBJS) 2>NUL

local_distclean:

local_test:
