TOPDIR = ..

-include $(TOPDIR)/makefiles/gmake/sub.mk

local_all:

local_clean:

local_install:
	$(INSTALL) -d -m 755 $(includedir)/smerp
	$(INSTALL) -m 644 *.h $(includedir)/smerp
	$(INSTALL) -m 644 *.hpp $(includedir)/smerp
