TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR)\include \
	/I"$(BOOST_INCLUDE_DIR)" \
	/I$(TOPDIR)\src\modules\database\oracle \
	/I"$(ORACLE_DIR)\sdk\include" \
	/I$(TOPDIR)\3rdParty\gtest\include

INCLUDE_LDFLAGS = \
	$(TOPDIR)\src\libwolframe \
	$(BOOST_LDFLAGS) \

INCLUDE_LIBS = \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\3rdParty\gtest\gtest-all.obj \
	"$(ORACLE_DIR)\sdk\lib\msvc\oci.lib" \
	kernel32.lib advapi32.lib Ws2_32.lib \
	wfsingleton.dll

CPP_OBJS = \
	PostgreSQLModuleFiles.obj

CPP_BINS = \
	oracleUnit.exe \
	dbPing.exe

TEST_CPP_BINS = \
	oracleUnit.exe

oracleUnit.exe: oracleUnit.obj OracleModuleFiles.obj
dbPing.exe: dbPing.obj

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test: dbPing.exe
	@-echo @echo off > test.bat
	@-echo copy "$(ORACLE_DIR)\*.dll" . >> test.bat
	@-echo dbping andreasbaumann.dyndns.org wolfusr wolfpwd orcl >> test.bat
	@-echo if errorlevel 1 goto skip >> test.bat
	@-echo echo continue >> test.bat
	@-echo oracleUnit >> test.bat
	@-echo goto end >> test.bat
	@-echo :skip >> test.bat
	@-echo echo No properly configured database for tests >> test.bat
	@-echo :end >> test.bat
	@test.bat

