'\" t
.\"     Title: wolframe
.\"    Author:  <contact@wolframe.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/29/2014
.\"    Manual: Wolframe User Manual
.\"    Source: wolframe.conf
.\"  Language: English
.\"
.TH "WOLFRAME" "5" "08/29/2014" "wolframe.conf" "Wolframe User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wolframe.conf \- Wolframe server configuration file
.SH "SYNOPSIS"
.HP \w'\fB/etc/wolframe/wolframe\&.conf\fR\ 'u
\fB/etc/wolframe/wolframe\&.conf\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the configuration options of the Wolframe system\&.
.SH "OPTIONS"
.PP
The configuration of the wolframe daemon or service is separated into sections\&. Some sections like \*(AqLoadModules\*(Aq always exist, others only exist if a module has been loaded\&.
.PP
We describe here only the standard settings which exist when no modules are loaded\&.
.PP
Check out the manpages of the wolframe modules
\fBwolframe-mod_XXXX\fR(5)
to see the available options in \*(Aqwolframe\&.conf\*(Aq when this module is loaded\&.
.SS "Global configuration options"
.PP
\fBServerSignature\fR
.RS 4
If set to \*(AqOn\*(Aq the server prints the name of the server as first element of the greeting in the protocol\&. Possible values are \*(AqOn\*(Aq or \*(AqOff\*(Aq\&.
.RE
.PP
\fBServerTokens\fR
.RS 4
Specifies how the server signature looks like when \*(AqServerSignature\*(Aq is set to \*(AqOn\*(Aq\&. Note: In a production environment you should be careful which information you reveal over the protocol to a possible attacker!
.sp
Possible values are:
.PP
None
.RS 4
Print nothing in the greeting line but the name of the software \*(AqWolframe\*(Aq\&.
.RE
.PP
ProductOnly
.RS 4
Print the name of the product implemented in Wolframe and Wolframe itself\&.
.RE
.PP
Major
.RS 4
Print only the major version of Wolframe\&.
.RE
.PP
Minor
.RS 4
Print major and minor version of Wolframe\&.
.RE
.PP
Revision
.RS 4
Print major, minor and revision of Wolframe\&.
.RE
.PP
Build
.RS 4
Print major, minor, revision and build of Wolframe\&.
.RE
.PP
OS
.RS 4
Print all information, including the operating system Wolframe is running on\&.
.RE
.sp
.RE
.SS "LoadModules"
.PP
The \*(AqLoadModules\*(Aq section contains directives to extend the system with loadable modules\&. Those can be new database modules, new scripting languages, document filters and processors, authentication/authorization/audit modules and other 3rdParty bindings, etc\&.
.PP
The following directives are valid in this section:
.PP
\fBDirectory \fR\fB\fImodule_directory\fR\fR
.RS 4
Load modules from directory
\fImodule_directory\fR
instead of searching for modules in the standard system module directory of Wolframe\&.
.RE
.PP
\fBModule \fR\fB\fImodule_name\fR\fR
.RS 4
Load module
\fImodule_name\fR\&. Note: You don\*(Aqt have to specify the module extension like \*(Aq\&.so\*(Aq\&.
.sp
The
\fImodule_name\fR
can contain a relative path\&. The module path is always caculated relatively to the
\fImodule_directory\fR
or to the default installation path for Wolframe modules\&.
.RE
.SS "Logging"
.PP
In the \*(AqLogging\*(Aq section you can configure ways of the Wolframe server to log\&.
.PP
There are logging channels named \*(Aq\fBStderr\fR\*(Aq (for foreground mode only!), \*(Aq\fBlogFile\fR\*(Aq to log to a simple text file and \*(Aq\fBsyslog\fR\*(Aq to log to the system log\&.
.PP
The following directives are valid in this section:
.PP
\fBLevel \fR\fB\fIlog_level\fR\fR
.RS 4
Log only messages up to the level
\fIlog_level\fR\&. Possible log levels are \*(AqFATAL\*(Aq, \*(AqALERT\*(Aq, \*(AqCRITICAL\*(Aq, \*(AqSEVERE\*(Aq, \*(AqERROR\*(Aq, \*(AqWARNING\*(Aq, \*(AqNOTICE\*(Aq, \*(AqINFO, \*(AqDEBUG\*(Aq, \*(AqTRACE\*(Aq, \*(AqDATA\*(Aq or \*(AqDATA2\*(Aq\&.
.sp
Note: This is the only directive which must be understood by all logging channels\&.
.RE
.PP
\fBFilename (logFile) \fR\fB\fIfile_name\fR\fR
.RS 4
Write log message to the file denoted by
\fIfile_name\fR\&.
.RE
.PP
\fBIdent (syslog) \fR\fB\fIident\fR\fR
.RS 4
The syslog identifier to tag the log entries with\&.
.RE
.PP
\fBFacility (syslog) \fR\fB\fIident\fR\fR
.RS 4
The syslog facility to tag the log entries with\&. Usual facilities are \*(AqLOCAL0\*(Aq to \*(AqLOCAL7\*(Aq, \*(AqUSER\*(Aq, \*(AqDAEMON\*(Aq or similar\&.
.sp
Consult the
\fBopenlog\fR(3)
man page to see what facilities are available on your system\&.
.RE
.SS "Listen"
.PP
The \*(AqListen\*(Aq section deals with network settings\&.
.PP
You can choose between a plain socket with the \*(Aq\fBSocket\fR\*(Aq directive or an encrypted socket with \*(Aq\fBSSLSocket\fR\*(Aq\&.
.PP
Note: \*(AqName\*(Aq, \*(AqAddress\*(Aq, \*(AqPort\*(Aq and \*(AqMaxConnections\*(Aq are common directives for both plain and encrypted sockets\&.
.PP
The following directives are valid in this section:
.PP
\fBMaxConnections \fR\fB\fImax_connections\fR\fR
.RS 4
Maximum number of simultaneous connections\&. This limits the number of clients which can use the server in parallel\&. If \*(Aq0\*(Aq is specified for
\fImax_connections\fR
or if the directive is absent, an operating system default is choosen\&.
.RE
.PP
\fBThreads \fR\fB\fImax_threads\fR\fR
.RS 4
Size of the pool of threads serving client connections\&. The default for
\fImax_threads\fR
is 4\&.
.RE
.PP
\fBAddress \fR\fB\fIip_address\fR\fR
.RS 4
IP address the server should listen to incoming connections\&.
\fIip_address\fR
is a valid IPv4 or IPv6 address\&. \*(Aq*\*(Aq denotes any address\&. \*(Aq0\&.0\&.0\&.0\*(Aq any IPv4 address\&. \*(Aq:::*\*(Aq any IPv6 address\&. \*(Aq127\&.0\&.0\&.1\*(Aq and \*(Aq::1\*(Aq denote the local loopback interface for IPv4 respectively IPv6\&.
.RE
.PP
\fBPort \fR\fB\fIport\fR\fR
.RS 4
Defines the port where the server listens on\&. We usually set
\fIport\fR
to 7661 for unencrypted connections and 7961 for encrypted connections\&.
.RE
.PP
\fBName "\fR\fB\fIinterface_name\fR\fR\fB"\fR
.RS 4
You can give interfaces a name, so they can be identified as group (for instance in authentication, autorization, auditing)\&. Naming interfaces is not required\&.
.RE
.PP
\fBMaxConnections \fR\fB\fImax_connections\fR\fR
.RS 4
Sets the maximum number of simultaneous connections locally for this interface\&.
.RE
.PP
\fBCertificate \fR\fB\fIserver\&.crt\fR\fR
.RS 4
The server certificate to use for encrypted connections\&. The format of the certificate is excepted to be
PEM\&.
.RE
.PP
\fBCertificate \fR\fB\fIserver\&.key\fR\fR
.RS 4
The server key to use for encrypted connections\&. The format of the key is excepted to be
PEM\&.
.RE
.PP
\fBCADirectory \fR\fB\fICA_directory\fR\fR
.RS 4
A directory holding CA certificate files\&.
.RE
.PP
\fBCAChainFile \fR\fB\fIchain_file\fR\fR
.RS 4
The
\fIchain_file\fR
holds the CA chain which is required to verify client certificates\&. The format of
\fIchain_file\fR
has to be
PEM\&.
.RE
.PP
\fBVerify\fR \fIOn\fR | \fIOff\fR
.RS 4
If switched on the server requires the client to send a valid client certificate which is checked by the server\&.
.RE
.SS "Daemon"
.PP
The \*(AqDaemon\*(Aq section sets the behaviour of the Wolframe server as a Unix daemon\&.
.PP
The following directives are valid in this section:
.PP
\fBUser \fR\fB\fIuser\fR\fR
.RS 4
Run the Wolframe daemon under permissions of the Unix user
\fIuser\fR\&.
.RE
.PP
\fBGroup \fR\fB\fIgroup\fR\fR
.RS 4
Run the Wolframe daemon under permissions of the Unix group
\fIgroup\fR\&.
.RE
.PP
\fBPidFile \fR\fB\fIpid_file\fR\fR
.RS 4
Where to store the PID daemon lock file\&. Note that
\fIpid_file\fR
must be in a location with enough rights for the
\fIuser\fR
to create the PID file!
.RE
.SS "Database"
.PP
The \*(AqDatabase\*(Aq section configures databases which can be used in programs, the AAAA layer, etc\&.
.PP
Each database module registers itself with a new section name, for instance the \*(Aqmod_db_sqlite3\&.so\*(Aq module registers a new section named
\fBSQLite\fR\&.
.PP
One parameter is supported for all database sections:
.PP
\fBIdentifier \fR\fB\fIidentifier\fR\fR
.RS 4
Register the configured database connection with name
\fIidentifier\fR\&. You can later reference it by that name when an identifier of a database connection is needed\&. This parameter is required\&.
.RE
.PP
Check out the manpages named
\fBwolframe-mod_db_XXXX\fR(5)
of the specific database module you want to use for a list of database specific options\&.
.SH "BUGS"
.PP
Find issues and bugs on
Github
at
\m[blue]\fB\%https://github.com/Wolframe/Wolframe/issues\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBwolframed\fR(8)
.SH "AUTHOR"
.PP
 <\&contact@wolframe\&.net\&>
.RS 4
This manual was written by the Wolframe Team\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2010-2014 Wolframe Team
.br
.PP
The authors grant permission to copy, distribute and/or modify this manual page under the terms of the GNU General Public License Version 3 or newer (GPLv3)\&.
.sp
