'\" t
.\"     Title: wolframe
.\"    Author:  <contact@wolframe.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/19/2014
.\"    Manual: Wolframe User Manual
.\"    Source: wolframe.conf
.\"  Language: English
.\"
.TH "WOLFRAME" "5" "02/19/2014" "wolframe.conf" "Wolframe User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wolframe.conf \- Wolframe server configuration file
.SH "SYNOPSIS"
.HP \w'\fB/etc/wolframe/wolframe\&.conf\fR\ 'u
\fB/etc/wolframe/wolframe\&.conf\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the configuration option of the Wolframe system\&.
.SS "Global configuration options"
.PP
\fBServerSignature\fR
.RS 4
If set to \*(AqOn\*(Aq the server prints the name of the server as first element of the greeting in the protocol\&. Possible values are \*(AqOn\*(Aq or \*(AqOff\*(Aq\&.
.RE
.PP
\fBServerTokens\fR
.RS 4
Specifies how the server signature looks like when \*(AqServerSignature\*(Aq is set to \*(AqOn\*(Aq\&. Note: In a production environment you should be careful which information you reveal over the protocol to a possible attacker!
.sp
Possible values are:
.PP
None
.RS 4
Print nothing in the greeting line but the name of the software \*(AqWolframe\*(Aq\&.
.RE
.PP
ProductOnly
.RS 4
Print the name of the product implemented in Wolframe and Wolframe itself\&.
.RE
.PP
Major
.RS 4
Print only the major version of Wolframe\&.
.RE
.PP
Minor
.RS 4
Print major and minor version of Wolframe\&.
.RE
.PP
Revision
.RS 4
Print major, minor and revision of Wolframe\&.
.RE
.PP
OS
.RS 4
Print all information, including the operating system Wolframe is running on\&.
.RE
.sp
.RE
.SH "OPTIONS"
.PP
The configuration of the wolframe daemon or service is separated into sections\&. Some sections like \*(AqLoadModules\*(Aq always exist, others only exist if a module has been loaded\&.
.SS "LoadModules"
.PP
The \*(AqLoadModules\*(Aq section contains directives to extend the system with loadable modules\&. Those can be new database modules, new scripting languages, document filters and processors, authentication/authorization/audit modules and other 3rdParty bindings, etc\&.
.PP
The following directives are valid in this section:
.PP
\fBdirectory \fR\fB\fImodule_directory\fR\fR
.RS 4
Load modules from directory
\fImodule_directory\fR
instead of searching for modules in the standard system module directory of Wolframe\&.
.RE
.PP
\fBmodule \fR\fB\fImodule_name\fR\fR
.RS 4
Load module
\fImodule_name\fR\&. Note: You don\*(Aqt have to specify the module extension like \*(Aq\&.so\*(Aq\&.
.sp
The
\fImodule_name\fR
can contain a relative path\&. The module path is always caculated relatively to the
\fImodule_directory\fR
or to the default installation path for Wolframe modules\&.
.RE
.SS "logging"
.PP
In the \*(Aqlogging\*(Aq section you can configure ways of the Wolframe server to log\&.
.PP
There are logging channels named \*(Aq\fBstderr\fR\*(Aq (for foreground mode only!), \*(Aq\fBlogFile\fR\*(Aq to log to a simple text file and \*(Aq\fBsyslog\fR\*(Aq to log to the system log\&.
.PP
The following directives are valid in this section:
.PP
\fBlevel \fR\fB\fIlog_level\fR\fR
.RS 4
Log only messages up to the level
\fIlog_level\fR\&. Possible log levels are \*(AqFATAL\*(Aq, \*(AqALERT\*(Aq, \*(AqCRITICAL\*(Aq, \*(AqSEVERE\*(Aq, \*(AqERROR\*(Aq, \*(AqWARNING\*(Aq, \*(AqNOTICE\*(Aq, \*(AqINFO, \*(AqDEBUG\*(Aq, \*(AqTRACE\*(Aq, \*(AqDATA\*(Aq or \*(AqDATA2\*(Aq\&.
.sp
Note: This is the only directive which must be understood by all logging channels\&.
.RE
.PP
\fBfilename (logFile) \fR\fB\fIfile_name\fR\fR
.RS 4
Write log message to the file denoted by
\fIfile_name\fR\&.
.RE
.PP
\fBident (syslog) \fR\fB\fIident\fR\fR
.RS 4
The syslog identifier to tag the log entries with\&.
.RE
.PP
\fBfacility (syslog) \fR\fB\fIident\fR\fR
.RS 4
The syslog facility to tag the log entries with\&. Usual facilities are \*(AqLOCAL0\*(Aq to \*(AqLOCAL7\*(Aq, \*(AqUSER\*(Aq, \*(AqDAEMON\*(Aq or similar\&.
.sp
Consult the
\fBopenlog\fR(3)
man page to see what facilities are available on your system\&.
.RE
.SS "daemon"
.PP
The \*(Aqdaemon\*(Aq section sets the behaviour of the Wolframe server as a Unix daemon\&.
.PP
The following directives are valid in this section:
.PP
\fBuser \fR\fB\fIuser\fR\fR
.RS 4
Run the Wolframe daemon under permissions of the Unix user
\fIuser\fR\&.
.RE
.PP
\fBgroup \fR\fB\fIgroup\fR\fR
.RS 4
Run the Wolframe daemon under permissions of the Unix group
\fIgroup\fR\&.
.RE
.PP
\fBpidFile \fR\fB\fIpid_file\fR\fR
.RS 4
Where to store the PID daemon lock file\&. Note that
\fIpid_file\fR
must be in a location with enough rights for the
\fIuser\fR
to create the PID file!
.RE
.SH "BUGS"
.PP
Find issues and bugs on
Github
at
\m[blue]\fB\%https://github.com/Wolframe/Wolframe/issues\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBwolframed\fR(8)
.SH "AUTHOR"
.PP
 <\&contact@wolframe\&.net\&>
.RS 4
This manual was written by the Wolframe Team\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2010-2014 Wolframe Team
.br
.PP
The authors grant permission to copy, distribute and/or modify this manual page under the terms of the GNU General Public License Version 3 or newer (GPLv3)\&.
.sp
