'\" t
.\"     Title: wolframe
.\"    Author:  <contact@wolframe.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/27/2014
.\"    Manual: Wolframe User Manual
.\"    Source: wolfpasswd
.\"  Language: English
.\"
.TH "WOLFRAME" "1" "02/27/2014" "wolfpasswd" "Wolframe User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wolfpasswd \- Wolframe password management program
.SH "SYNOPSIS"
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR \fB\-D\ \fR\fB\fIpasswordfile\fR\fR\fB\ \fR\fB\fIusername\fR\fR
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR [\fB\-c\fR] [\fB\-d \fR\fB\fIdays\fR\fR] \fIpasswordfile\fR \fIusername\fR [\fIuser\ info\fR]
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR \fB\-b\fR [\fB\-c\fR] [\fB\-d \fR\fB\fIdays\fR\fR] \fIpasswordfile\fR \fIusername\fR \fIpassword\fR [\fIuser\ info\fR]
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR \fB\-n\fR [\fB\-s \fR\fB\fIsalt\fR\fR] [\fB\-d \fR\fB\fIdays\fR\fR] \fIusername\fR [\fIuser\ info\fR]
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR \fB\-n\fR \fB\-b\fR [\fB\-s \fR\fB\fIsalt\fR\fR] [\fB\-d \fR\fB\fIdays\fR\fR] \fIusername\fR \fIpassword\fR [\fIuser\ info\fR]
.HP \w'\fBwolfpasswd\fR\ 'u
\fBwolfpasswd\fR \fB\-h\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBwolfpasswd\fR
command\&.
.PP
\fBwolfpasswd\fR
is a tool to manage user credentials in the Wolframe system\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. A summary of options is included below\&. For a complete description, see the
\fBinfo\fR(1)
files\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options\&.
.RE
.PP
\fB\-c\fR, \fB\-\-create\fR
.RS 4
Create the file if it doesn\*(Aqt exist\&.
.RE
.PP
\fB\-s\fR, \fB\-\-salt \fR\fB\fIsalt\fR\fR
.RS 4
Use the specified salt (only valid with \-\-display\-only)\&.
.RE
.PP
\fB\-d\fR, \fB\-\-days \fR\fB\fIdays\fR\fR
.RS 4
Set the password expiration after
\fIdays\fR
days\&. The default (=0) means don\*(Aqt expire\&.
.RE
.PP
\fB\-n\fR, \fB\-\-display\-only\fR
.RS 4
Don\*(Aqt update the password file; display results on stdout\&.
.RE
.PP
\fB\-b\fR, \fB\-\-batch\fR
.RS 4
Use the password from the command line instead of prompting for it\&.
.RE
.PP
\fB\-D\fR, \fB\-\-delete\fR
.RS 4
Delete the specified user\&.
.RE
.SH "DIAGNOSTICS"
.PP
The following diagnostics may be issued on
stderr:
.PP
password file \*(Aq\fIpasswordfile\fR\*(Aq does not exist\&.
.RS 4
The password file doesn\*(Aqt exist\&. Use \-c/\-\-create to create it first\&.
.RE
.PP
\fBwolfpasswd\fR
provides some return codes, that can be used in scripts:
.\" line length increase to cope w/ tbl weirdness
.ll +(\n(LLu * 62u / 100u)
.TS
ll.
\fICode\fR	\fIDiagnostic\fR
T{
\fB0\fR
T}	T{
Program exited successfully\&.
T}
T{
\fB1\fR
T}	T{
An error occurred\&.
T}
.TE
.\" line length decrease back to previous value
.ll -(\n(LLu * 62u / 100u)
.sp
.SH "BUGS"
.PP
Find issues and bugs on
Github
at
\m[blue]\fB\%https://github.com/Wolframe/Wolframe/issues\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBwolframed\fR(8)
.SH "AUTHOR"
.PP
 <\&contact@wolframe\&.net\&>
.RS 4
This manual was written by the Wolframe Team\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2010-2014 Wolframe Team
.br
.PP
The authors grant permission to copy, distribute and/or modify this manual page under the terms of the GNU General Public License Version 3 or newer (GPLv3)\&.
.sp
