TOPDIR = ..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. /I"$(LIBXML2_DIR)\include" \
	/I"$(LIBXML2_DIR)\include\libxml2" \
	/I"$(LIBXSLT_DIR)\include" \
	/I"$(WIN_ICONV_DIR)"

# Note: libraries are picked automatically on Windows!
INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	"$(LIBXML2_DIR)\lib\libxml2.lib" \
	"$(LIBXSLT_DIR)\lib\libxslt.lib"

TEST_CPP_BINS = \
	testlibxslt1.exe

all: $(OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testlibxslt1.exe: testlibxslt1.obj

local_all:

local_clean:
	@-erase test.RES 2>NUL

local_distclean:

local_test:
	@-copy "$(WIN_ICONV_DIR)\iconv.dll" .
	@-copy "$(LIBXML2_DIR)\bin\libxml2.dll" .
	@-copy "$(LIBXSLT_DIR)\lib\libxslt.dll" .
	@-testlibxslt1 test1.xslt test1.xml > test1.RES
