TOPDIR = ..

SUBDIRS =

PACKAGE_NAME = wolframe

-include $(TOPDIR)/makefiles/gmake/platform.mk

INCLUDE_DIRS =

INCLUDE_LDFLAGS =

INCLUDE_LIBS =

STATIC_LIB = libcjson.a

DYNAMIC_LIB = libcjson.so
DYNAMIC_LIB_MAJOR = 0
DYNAMIC_LIB_MINOR = 11
DYNAMIC_LIB_PATCH = 0

OBJS = \
	cJSON.o

-include $(TOPDIR)/makefiles/gmake/sub.mk

ALL_CFLAGS = $(OPTFLAGS) -Wall -I. -I../include $(INCLUDE_DIRS) $(INCLUDE_CFLAGS)

local_all:

local_clean:

local_distclean:

local_install:

local_uninstall:

local_test:
