TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CFLAGS = \
	/D_WIN32_WINNT=0x504 \
	/wd4146

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504 \
	/wd4146

INCLUDE_DIRS = \
	/I. /I$(TOPDIR)\libgmp

INCLUDE_LDFLAGS =

INCLUDE_LIBS = \
	$(TOPDIR)\libgmp\mpz\mpz.lib \
	$(TOPDIR)\libgmp\gmpcommon.lib \
	$(TOPDIR)\libgmp\mpn\mpn.lib

TEST_CPP_BINS = \
	testlibgmp.exe

all: $(TEST_CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

testlibgmp.exe: testlibgmp.obj

local_all:

local_clean:
	@-erase test.bat 2>NUL

local_distclean:

local_test:
	@-echo @echo off > test.bat
	@-echo testlibgmp 4 5 >> test.bat
	@-echo testlibgmp 424234238490238409238402380482304 52342342342342342342342323 >> test.bat
	@-test.bat
